### ISSUE TITLE
OBJECT_LITERAL_EXPRESSION

### ISSUE THREAD

**Issue by kornicameister** [Fedott/WebStormRequireJsPlugin#39]
Hi there,

After upgrading RequireJS plugin to the newest version it looks like something got broken as I am receiving following error in the IntelliJ plugin. I couldn't have located appropriate repository for IntelliJ version so I am assuming this one is the right one, especially that plugin [previous version] has been used flawlessly for about 6 months.

My OS/IDE details:
- Widows 8.1 64b
- Intellij IDEA Ultimate, Build 141.2110
- Plugin version: 0.21

Alright, here is the stacktrace:
`````
OBJECT_LITERAL_EXPRESSION
java.lang.NoSuchFieldError: OBJECT_LITERAL_EXPRESSION
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:325)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:296)
	at requirejs.RequirejsProjectComponent.getBaseUrlPath(RequirejsProjectComponent.java:259)
	at requirejs.RequirejsProjectComponent.requireResolve(RequirejsProjectComponent.java:674)
	at requirejs.RequirejsReference.resolve(RequirejsReference.java:40)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.hasBadResolve(JSAnnotatingVisitor.java:267)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.checkReferences(JSAnnotatingVisitor.java:232)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.visitJSLiteralExpression(JSAnnotatingVisitor.java:162)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.accept(JSLiteralExpressionImpl.java:92)
	at com.intellij.lang.javascript.validation.JSAnnotatingVisitor.annotate(JSAnnotatingVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:346)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:275)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:272)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1107)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:282)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
````

**Comment by prantlf** [comment]
I can confirm this error turning up first in WebStorm 10 EAP (140.2424).  The plugin works well with the same settings in WebStorm 9.0.3 (139.1112).  Apparently `com.intellij.lang.javascript.JSElementTypes` does not contain `OBJECT_LITERAL_EXPRESSION` anymore in the new WebStorm build...

My project structure:

    config-editor.js
    [src]
      [lib]
        require.js
        text.js
        css.js
        hbs.js
        i18n.js
        jquery.js
        ...

RequireJS plugin settings:

![image](https://cloud.githubusercontent.com/assets/733193/6199521/46f654da-b449-11e4-9447-2c822fa9bcf2.png)

The config.editor.js file content:

    require.config({
      paths: {
        csui: "src", // maps the common 'csui' prefix to the module root directory
        txt: "src/lib/text",
        css: "src/lib/css",
        hbs: "src/lib/hbs",
        i18n: "src/lib/i18n"
      }
    });

Sample module `src/widgets/test.js`:

    define(['csui/lib/jquery', ...], function ($) {
      ...
    });

[Log from the WebStorm startup with the RequireJS plugin crash](http://pastebin.com/VNj3exh2)

**Comment by Fedott** [comment]
Thanks for reports.
I will fix this in next version.

**Comment by prantlf** [comment]
As the WebStorm 10 RC is out, are planning to release the 0.22 version soon?  Thanks!

Your plugin is really handy, because WebStorm does not support module paths from the config...

**Comment by Fedott** [comment]
Hi.
I will try fix this problem soon.

**Comment by mr-moon** [comment]
@Fedott , thanks for the update. Just wanted to know that this is still relevant for IntelliJ IDEA 14.1.

**Comment by Fedott** [comment]
Hi, i fixed this problem.
Version 0.22 available now. Please check.

**Comment by prantlf** [comment]
It works well, thanks!  The Go to Declaration changed; it does not offer the function object declaration anymore, if it is in a different file:

![image](https://cloud.githubusercontent.com/assets/733193/6926929/24deef1e-d7ea-11e4-8682-aa3bcf5db01a.png)

But the feature Go to Type Declaration goes right to the file with the declaration, withotu any context menu:

![image](https://cloud.githubusercontent.com/assets/733193/6926956/4670ba22-d7ea-11e4-941e-d4b5ba0105cd.png)

Just one key to hit, even better! :-)
