### ISSUE TITLE
Strange error at startup

### ISSUE THREAD

**Issue by pesh1983** [Fedott/WebStormRequireJsPlugin#48]
```java
null
java.lang.NullPointerException
	at requirejs.RequirejsProjectComponent.getJSPropertyLiteralValue(RequirejsProjectComponent.java:576)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:599)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:605)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:605)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:605)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:605)
	at requirejs.RequirejsProjectComponent.parseRequireJsPaths(RequirejsProjectComponent.java:605)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:409)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:430)
	at requirejs.RequirejsProjectComponent.findAndParseConfig(RequirejsProjectComponent.java:352)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:335)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:317)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseMainJsFile(RequirejsProjectComponent.java:312)
	at requirejs.RequirejsProjectComponent.parseRequirejsConfig(RequirejsProjectComponent.java:296)
	at requirejs.RequirejsProjectComponent.getBaseUrlPath(RequirejsProjectComponent.java:259)
	at requirejs.RequirejsProjectComponent.requireResolve(RequirejsProjectComponent.java:674)
	at requirejs.RequirejsReference.resolve(RequirejsReference.java:40)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getTypeIfAmdModuleReference(JSTypeEvaluator.java:1107)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processParameterType(JSTypeEvaluator.java:1059)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromVariableResolveResult(JSTypeEvaluator.java:784)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromResolveResult(JSTypeEvaluator.java:766)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:726)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:192)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:89)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.doResolve(JSReferenceExpressionResolver.java:111)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2640)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:413)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.processParametersForUsedArgument(JSResolveUtil.java:1435)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.findParameterForUsedArgument(JSResolveUtil.java:1473)
	at com.intellij.lang.javascript.psi.ExpectedTypeEvaluator.visitJSArgumentList(ExpectedTypeEvaluator.java:52)
	at com.intellij.lang.javascript.psi.impl.JSArgumentListImpl.accept(JSArgumentListImpl.java:54)
	at com.intellij.lang.javascript.psi.ExpectedTypeEvaluator.findExpectedType(ExpectedTypeEvaluator.java:34)
	at com.intellij.lang.javascript.dialects.JSDialectSpecificHandlersFactory.findExpectedType(JSDialectSpecificHandlersFactory.java:55)
	at com.intellij.lang.javascript.psi.resolve.JSPropertyNameResolver.doResolve(JSPropertyNameResolver.java:32)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2640)
	at com.intellij.lang.javascript.psi.impl.JSPropertyNameReference.multiResolve(JSPropertyNameReference.java:54)
	at com.intellij.lang.javascript.psi.impl.JSPropertyNameReference.resolve(JSPropertyNameReference.java:43)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:70)
	at com.intellij.codeInsight.intention.impl.AddAnnotationIntention.isAvailable(AddAnnotationIntention.java:51)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:125)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:106)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:294)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:150)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:293)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:188)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```
It happens after startup. If you need any other info I'm ready to provide it.

**Comment by Fedott** [comment]
Hello! Thanks for your report.
Please show me you requirejs config(section "paths").

**Comment by pesh1983** [comment]
Hi! Here it is
