### ISSUE TITLE
java.lang.StackOverflowError in RubyMine EAP Build RM-143.380.14 

### ISSUE THREAD

**Issue by brucek** [Fedott/WebStormRequireJsPlugin#58]
OSX 10.11.1
JRE 1.8.0-40-release-b92

When I open any require.js project, I get StackOverflow errors, some samples:

-------------------------------------------------------------------
null
java.lang.StackOverflowError
	at com.intellij.openapi.module.ModuleManager.getInstance(ModuleManager.java:42)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.b(ProjectRootManagerImpl.java:451)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.getContentRoots(ProjectRootManagerImpl.java:168)
	at requirejs.RequirejsProjectComponent.findPathInContentRoot(RequirejsProjectComponent.java:199)
	at requirejs.RequirejsProjectComponent.getWebDir(RequirejsProjectComponent.java:161)
	at requirejs.RequirejsProjectComponent.getWebDir(RequirejsProjectComponent.java:170)
	at requirejs.RequirejsProjectComponent.findPathInWebDir(RequirejsProjectComponent.java:177)
	at requirejs.RequirejsProjectComponent.getBaseUrlPath(RequirejsProjectComponent.java:270)
	at requirejs.Path.probeResolveBasic(Path.java:188)
	at requirejs.Path.resolve(Path.java:102)
	at requirejs.RequirePaths.resolve(RequirePaths.java:36)
	at requirejs.Path.probeResolveRequirePath(Path.java:178)
	at requirejs.Path.resolve(Path.java:107)
	at requirejs.RequirePaths.resolve(RequirePaths.java:36)
	at requirejs.Path.probeResolveRequirePath(Path.java:178)
	at requirejs.Path.resolve(Path.java:107)
[...etc...]
-------------------------------------------------------------------

null
java.lang.StackOverflowError
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:126)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:143)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:91)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:398)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:58)
	at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:370)
	at requirejs.RequirejsProjectComponent.findPathInContentRoot(RequirejsProjectComponent.java:202)
	at requirejs.RequirejsProjectComponent.getWebDir(RequirejsProjectComponent.java:161)
	at requirejs.RequirejsProjectComponent.getWebDir(RequirejsProjectComponent.java:170)
	at requirejs.RequirejsProjectComponent.findPathInWebDir(RequirejsProjectComponent.java:177)
	at requirejs.RequirejsProjectComponent.getBaseUrlPath(RequirejsProjectComponent.java:270)
	at requirejs.Path.probeResolveBasic(Path.java:188)
	at requirejs.Path.resolve(Path.java:102)
	at requirejs.RequirePaths.resolve(RequirePaths.java:36)
	at requirejs.Path.probeResolveRequirePath(Path.java:178)
	at requirejs.Path.resolve(Path.java:107)
	at requirejs.RequirePaths.resolve(RequirePaths.java:36)
	at requirejs.Path.probeResolveRequirePath(Path.java:178)
	at requirejs.Path.resolve(Path.java:107)
	at requirejs.RequirePaths.resolve(RequirePaths.java:36)
	at requirejs.Path.probeResolveRequirePath(Path.java:178)
	at requirejs.Path.resolve(Path.java:107)
[...etc...]

**Comment by tiger-seo** [comment]
+1 in PhpStorm 10.0.3
