### ISSUE TITLE
NullPointerException every few seconds

### ISSUE THREAD

**Issue by AlexandreBonneau** [Fedott/WebStormRequireJsPlugin#63]
Once PhpStorm reach 100 exceptions with the same plugins, it stops logging them.
Since PhpStorm 2016.1, that requirejs plugin output a NullPointerException every 2 to 4 seconds.

Here is one trace :
`null
java.lang.NullPointerException
    at requirejs.Path.isAbsolutePath(Path.java:68)
    at requirejs.Path.resolve(Path.java:87)
    at requirejs.RequirePaths.resolve(RequirePaths.java:36)
    at requirejs.Path.probeResolveRequirePath(Path.java:177)
    at requirejs.Path.resolve(Path.java:106)
    at requirejs.RequirejsProjectComponent.requireResolve(RequirejsProjectComponent.java:657)
    at requirejs.RequirejsReference.resolve(RequirejsReference.java:40)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromAmdModuleReference(JSTypeEvaluator.java:1113)
    at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.addTypeFromAmdModuleReference(TypeScriptTypeEvaluator.java:521)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromVariableResolveResult(JSTypeEvaluator.java:1017)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.addTypeFromResolveResult(JSTypeEvaluator.java:1000)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:932)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:269)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:104)
    at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.doResolve(JSReferenceExpressionResolver.java:84)
    at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2663)
    at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:427)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getResolveResultsFromQualifier(JSTypeEvaluator.java:966)
    at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.getResolveResultsFromQualifier(TypeScriptTypeEvaluator.java:486)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:909)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:269)
    at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:104)
    at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.doResolve(JSReferenceExpressionResolver.java:84)
    at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2663)
    at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:427)
    at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.isReferenceTo(JSResolveUtil.java:1932)
    at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.isReferenceTo(JSReferenceExpressionImpl.java:255)
    at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$15.execute(PsiSearchHelperImpl.java:762)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:129)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
    at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.processInReadAction(PsiSearchHelperImpl.java:230)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.processInReadAction(PsiSearchHelperImpl.java:226)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
    at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$14.process(PsiSearchHelperImpl.java:725)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$14.process(PsiSearchHelperImpl.java:719)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.compute(PsiSearchHelperImpl.java:385)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.compute(PsiSearchHelperImpl.java:367)
    at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:367)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$100(PsiSearchHelperImpl.java:68)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:314)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:309)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)`

Would you see what is causing it?
If you need more info, don't hesitate to contact me.

**Comment by AlexandreBonneau** [comment]
This bug affects version 0.25, used with PhpStorm 2016.1.2.
